### ISSUE TITLE
About problem of toy_data_creater.py

### ISSUE THREAD

**Issue by dongqing065269** [rahulkulhalli/SkinLegion#1]
Hello ,Can you explain how to use each script and program, what is their order of use? Thanks!

**Comment by dongqing065269** [comment]
And when i run the file of toy_data_data_creater.py, there is an error of "[WinError 3] 系统找不到指定的路径。: 'E:\\GoogleDownload\\DATA\\ISIC2018\\output\\output\\nv_non_nv\\train"   the system can not file the specified path...can you help me find out where is wrong? thanks very much!

**Comment by rahulkulhalli** [comment]
Hi @dongqing065269, the code is not generic as of now. We will be making it as generic as possible in a little while. Till then, please replace the hardcoded paths with your own paths. :)

**Comment by dongqing065269** [comment]
Hi, i use your latest code,and when i run toy_data_creater.py, there still got the error of "FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'E:/GoogleDownload/DATA/datasets/a/toy/train/dir'",
and i can not create the  my path/toy/train/dir

**Comment by dongqing065269** [comment]
Hi, i use your latest code,and when i run toy_data_creater.py, there still got the error of "FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'E:/GoogleDownload/DATA/datasets/a/toy/train/dir'",
and i can not create the  my path/toy/train/dir

**Comment by rahulkulhalli** [comment]
@dongqing065269 We will be updating our documentation shortly.
